name: Build PBR

on:
  schedule:
    - cron: "2 0/1 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: download cidr
      run: |
        chmod +x ros-dpbr.sh
        ./ros-dpbr.sh
        
    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y%m%d-%H%M')" >> $GITHUB_OUTPUT
        
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "release-${{ steps.date.outputs.date }}"
        release_name: "China Route ${{ steps.date.outputs.date }}"
        body: |
          Automatic update of China IP route list.
          Generated on: ${{ steps.date.outputs.date }}
        draft: false
        prerelease: false
        
    - name: Upload CN.rsc to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./CN.rsc
        asset_name: CN.rsc
        asset_content_type: text/plain
